### ISSUE TITLE
[Bug]: no lyrics when in fullscreen

### ISSUE THREAD

**Issue by jmggithub1** [daksh2k/Spicetify-stuff#29] opened 2022-11-07 09:33 UTC
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.97.962.g24733a46
- Spicetify version: v2.14.1
```

### 📝 Description

when i go to fullscreen theres no lyrics even if the lyrics setting is on.

**Comment by SIMULATAN** [comment] 2022-11-07 09:36
Install the lyrics+ extension
Duplicate of #27 and #15

**Closed** 2022-11-14 08:40 UTC
Labels: bug
