### ISSUE TITLE
[Feature Request]: Add queue list

### ISSUE THREAD

**Issue by ChickChuck2** [daksh2k/Spicetify-stuff#54] opened 2023-03-16 23:40 UTC
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

in the FullScreen extension, there could be an option to show the sounds in the queue, in case the person wants to see the lyrics, list of sounds and MODIFY THE QUEUE
I hope it's a good idea

![image](https://user-images.githubusercontent.com/48648882/225775783-77a3bf9b-3523-4399-9857-405b44508808.png)

**Comment by daksh2k** [comment] 2023-03-17 06:59
Duplicate of #12

**Closed** 2023-03-17 07:00 UTC
Labels: enhancement
