### ISSUE TITLE
[Bug]: Lyrics not avaible

### ISSUE THREAD

**Issue by witekkkk** [daksh2k/Spicetify-stuff#148] opened 2024-02-16 22:14 UTC
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
Spicetify 2.31.3
Extentions: fullScreen.js
Custom apps: marketplace, lyrics-plus
```

### 📝 Description

Hi!
So basically my spicetify was working well till now... When I'm using fullscreen lyrics arent avaible. I read that I have to download lyrics-plus and thats what I did (still not working)
Hope for your response, 
Goodbye

### 📸 Screenshots

![image](https://github.com/daksh2k/Spicetify-stuff/assets/160285872/3922aefd-17a8-4e2d-97b4-468d335ea143)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/160285872/80f068c1-2185-4be6-a539-686cc30453ad)

**Comment by SIMULATAN** [comment] 2024-02-17 08:41
> I know it's an issue with `lyrics-plus` extension not working in spotify `1.2.31`, check https://github.com/spicetify/spicetify-cli/issues/2844 for any updates.

Most likely a duplicate of #147

**Comment by witekkkk** [comment] 2024-02-17 23:00
Yep, I downloaded the 1.2.30 version and its working, thanks so much for help

**Closed** 2024-02-21 09:05 UTC
Labels: bug
