### ISSUE TITLE
[Feature Request]: [Queue Implementation?]

### ISSUE THREAD

**Issue by N72826** [daksh2k/Spicetify-stuff#144] opened 2024-02-07 14:19 UTC
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Would there be a way to implement a queue that ideally would be interactive? This would be greatly appreciated so that I don't have to exit full screen in order to add/remove the current song to a playlist or remove/shift items in the queue. For example, Plexamp's queue allows me to remove/shift items in the queue next to the music that is currently playing, I attached an image of how that looks in the additional information section.

### ➕ Additional Information

**(Image of Plexamp's queue implementation.)**
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/21070431/cf480614-216f-43f0-90b7-6336974d68c1)

**Comment by daksh2k** [comment] 2024-02-11 14:08
Duplicate of #12 , really time consuming to implement though, so don't know when I'll get the time to add it in the extension.

**Closed by daksh2k** 2024-02-11 14:08 UTC
Labels: enhancement
