### ISSUE TITLE
[Bug]: Background choice is lower quality.

### ISSUE THREAD

**Issue by UP5-5** [daksh2k/Spicetify-stuff#51] opened 2023-03-03 20:47 UTC
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.6.863 (March, 3rd 2023)
- Spicetify version: v2.16.2
```

### 📝 Description

List steps to reproduce the error: Just enter full screen mode and the artist artwork and album art is lower quality (pixelated).
I've tried restarting spotify but the issue still there. I didn't have this issue on any of the previous versions, only after updating to the latest version.

A good example of the problem: 
![image](https://user-images.githubusercontent.com/126914274/222825181-2fdcb32e-9e27-4468-bc79-28cb51e0e1de.png)
As you can see it's easier to tell around letters that the artist artwork and/or album art is lower quality.
I assume this will be a quick fix (That's just what I think. Idk if I am wrong or right).

**Comment by daksh2k** [comment] 2023-03-05 18:32
Hi @UP5-5, is this the case for all the tracks or only some particular ones?
The images are returned by Spotify, for artist images I am explicitly using the higher quality image used by them for big TV's, so ideally this shouldn't be an issue.

**Comment by UP5-5** [comment] 2023-03-05 22:54
This issue is for all the tracks and artists (as far as i know and checked out). 
I know the images that are provided are high quality but when you enter full screen mode the quality gets reduced, that's the strange part.

**Comment by daksh2k** [comment] 2023-03-06 13:16
I am not able to reproduce this issue, might be some other reason you are facing this issue, if you are talking about the blur on the right side, that is caused by lyrics and that can be turned off in `lyrics-plus` settings. Your display might be too big, so the scaling issue might be there.

- Otherwise like this [image](https://i.scdn.co/image/ab67616d0000b273b4d0d46e3a2e317576648b12) is the default highest resolution provided by Spotify for album art, and that is used in the extension. 
- For the artist's background, varies according to the artist.

**Comment by UP5-5** [comment] 2023-03-06 23:09
I have uninstalled Spotify, Spicetify, full screen extension and every other extensions also (basically a fresh start) but I encounter the same problem. That's with only having full screen extension added (other than the ones that come in bundled with Spicetify).

As for my display, I have 1080p 16:9 aspect ratio screen and I have using the same display and didn't have any issue before. 
 
I understand that for the artist's background a artist can just upload a low quality background and call it a day (if that was the case) but it doesn't make sense that every other artist's background also becomes lower quality. To fact check this I played several artists on my TV and the background for all of the artist are high quality compared to background shown in the extension.
The screen resolution and aspect ratio for my TV is the same as my display.

**Comment by daksh2k** [comment] 2023-03-07 10:33
Interesting, that's really weird, I'll investigate a bit, for artist artwork, I can't reproduce this issue, and there are no other user reports similar to this, so it might be a little difficult to fix. 

**Meanwhile, can you share a video of this happening?**

Is the same issue occurring for default mode also where album art is used as a background?

**Comment by UP5-5** [comment] 2023-03-09 20:13
As u can see in the [video](https://drive.google.com/file/d/1_wnjbhwUxSlyf-hIEESaIkU0JYDeYJN6/view?usp=sharing) I first started of by booting into a new clean start to Spotify/Spicetify then I installed 2 extensions and a theme that puts the artist's background as the background in their artist page in order to demonstrate the artist's background is high quality even when it's displayed in full screen.
Lastly I show the difference in quality when switching between full screen/default mode.

**This is also the case for album art but I don't count is as a issue**. To begin with in the earlier versions, album art was already moderately low quality (when displayed in full screen/default mode). Reason being I think that there's a limit how much pixel by pixel a album art can be before it can not be uploaded. So when upscaling the album art becomes low quality. I'm guessing the upload limit for album art is 1000×1000.

**Comment by daksh2k** [comment] 2023-05-20 14:35
Hi, I appreciate your support and input on this matter. It seems that the issue might be invalid because the screens were compared in different scenarios. The presence of a shadow in the theme may have obscured the true quality of the artist's art. To obtain accurate results, it's important to test both screens under the same conditions.

In the default mode, the background is intentionally blurred and set to 70% brightness, which represents the standard setting. Conversely, in TV Mode, the background brightness is set to 40% with no blur, also as per the default setting.

While advanced options are available for advanced customization, it's worth noting that they may not always deliver optimal performance in all combinations of settings. These options come with sensible defaults to ensure a satisfactory experience for the average user, eliminating the need for extensive tweaking.

I have thoroughly tested the system, following the steps you provided, and found consistent behaviour. I have also attached some screenshots for your reference.

However, I did notice a minor decrease in quality due to the use of  [Canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) for backgrounds, which is necessary for smooth song change animations. Additionally, there were some resizing and scaling issues due to unconventional screen sizes, although these issues were not significant.

If you have any further information to add, please feel free to leave a comment. For now, I am closing this issue.

### Theme

<img width="1904" alt="Screenshot 2023-05-20 at 7 35 08 PM" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/46df9dc1-6624-4c92-a232-5cd827d71c74">

### Extension
<img width="1904" alt="Screenshot 2023-05-20 at 7 35 04 PM" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/8b2fef2a-70e4-4509-8df0-248a32146d76">

<hr>

### Theme

![Screenshot 2023-05-20 at 7 24 19 PM](https://github.com/daksh2k/Spicetify-stuff/assets/42179185/f2432229-7549-435d-bf79-9f54f7b40e2c)

### Extension

![Screenshot 2023-05-20 at 7 27 36 PM](https://github.com/daksh2k/Spicetify-stuff/assets/42179185/2a32924a-b4f6-4d64-8f52-ce0e2bae537c)

**Closed by daksh2k** 2023-05-20 14:35 UTC
Labels: bug, full screen, in development
