### ISSUE TITLE
NO LYRICS POPS UP IN FULLSCREEN 

### ISSUE THREAD

**Issue by ANii693** [daksh2k/Spicetify-stuff#33] opened 2022-11-24 11:47 UTC
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: LATEST VERSION (JUST INSTALLED)
- Spicetify version: LATEST VERSION (JUST INSTALLED)
```

### 📝 Description

on switching to full screen(extension) no lyrics pops up
screenshots attached 

### 📸 Screenshots

![Screenshot (169)](https://user-images.githubusercontent.com/118979320/203776062-5d35b87f-1723-4fa7-b134-ae54c04ee0bf.png)
![Screenshot (170)](https://user-images.githubusercontent.com/118979320/203776093-520bbd0f-9002-4e78-aabe-3db44dfae799.png)

**Comment by SIMULATAN** [comment] 2022-11-24 11:53
Install lyrics+
See [this note](https://github.com/daksh2k/Spicetify-stuff/blob/master/EXTENSIONS.md#note-you-need-lyrics-plus-custom-app-for-showing-lyrics-in-the-extension)
Duplicate of #15 #27

**Closed** 2022-11-29 14:41 UTC
Labels: bug

**Comment by ANii693** [comment] 2022-12-06 13:23
THANK YOU
