### ISSUE TITLE
[Feature Request]: Visualizer in Fullscreen

### ISSUE THREAD

**Issue by Kingkiller987** [daksh2k/Spicetify-stuff#90] opened 2023-06-14 23:05 UTC
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

In place of the lyrics, you can have the option to put a visualizer there instead (Or you can be able to have both you would just have to put the visualizer somewhere else probably)

**Comment by daksh2k** [comment] 2023-06-28 10:41
Duplicate of #58

**Closed by daksh2k** 2023-06-28 10:41 UTC
Labels: enhancement
