### ISSUE TITLE
[Bug]: Lyrics disappearing in full screen mode

### ISSUE THREAD

**Issue by Ethos070** [daksh2k/Spicetify-stuff#171] opened 2024-07-05 10:16 UTC
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.40.599.g606b7f29

Spicetify v2.36.14
```

### 📝 Description

When i open the fullscreen mode i can see the lyrics for a moment but then they disappear instantly.
I have lyrics plus installed and the extension works by itself.

### 📸 Screenshots

![immagine](https://github.com/daksh2k/Spicetify-stuff/assets/64336910/c3054fb9-cf41-47da-82e3-c70f32d0220e)
![2024-07-05 12-10-38](https://github.com/daksh2k/Spicetify-stuff/assets/64336910/7ed3694c-cd19-4609-9618-27cba47afbe8)

**Comment by daksh2k** [comment] 2024-07-05 17:31
Check https://github.com/daksh2k/Spicetify-stuff/issues/167#issuecomment-2199480598
Duplicate of #167

**Closed by daksh2k** 2024-07-05 17:31 UTC
Labels: bug
